name: cliffs
version: 0.1.0.0
github: "jisantuc/cliffs"
license: MIT
author: "James Santucci"
maintainer: "james.santucci@gmail.com"
copyright: "2021 James Santucci"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jisantuc/cliffs#readme>

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - base >= 4.7 && < 5
  - brick
  - command
  - directory
  - filepath
  - microlens
  - text
  - vector
  - vty

library:
  source-dirs: src

executables:
  cliffs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cliffs

tests:
  cliffs-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cliffs
