name: CD

on:
  pull_request:
  push:
    tags:
      - v*

jobs:
  cabal:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install package
        id: package-installation
        run: nix-env -i -f default.nix && echo "::set-output name=BINARY_PATH::$(which cliffs)"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.package-installation.outputs.BINARY_PATH }}
