name: CD

on:
  pull_request:
  push:
    tags:
      - v*

jobs:
  cabal:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Use cachix
        uses: cachix/cachix-action@v10
        with:
          name: jisantuc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install package
        run: nix-env -i -f default.nix

      - name: Locate package binary
        id: package-location
        run: echo "::set-output name=BINARY_PATH::$(which cliffs)"

      - name: Echo binary location
        run: echo ${{ steps.package-location.outputs.BINARY_PATH }}

      - name: Read binary location link
        run: readlink -f ${{ steps.package-location.outputs.BINARY_PATH }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.package-location.outputs.BINARY_PATH }}
