name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      
      - name: Use cachix
        uses: cachix/cachix-action@v10
        with:
          name: jisantuc
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build package
        run: nix-build

      - name: Test
        run: |
          nix-shell --run 'cabal test all --enable-coverage'
